### ISSUE TITLE
Handle tfwx files

### ISSUE THREAD

**Issue by pascalhorton** [terranum-ch/ToolMap#397]
Either support these files or warn the user that it cannot be displayed.

**Comment by lucsch** [comment]
tfwx files are world file approximation.

See here for more information http://webhelp.esri.com/arcgisdesktop/9.3/index.cfm?pid=3034&topicname=World_files_for_raster_datasets

a aux.xml file should be also available for thoses files and GDAL is normally using this file for the georeferencing : http://www.gdal.org/frmt_gtiff.html

To fully support such raster, they should be "rectified" instead of georeferencing them. A new resampled image will then be created, which can be accurately georeferenced using a world file. 

It's similar to the rotation problem described in ToolMap's help: http://toolmap.readthedocs.io/en/latest/faq/rotation.html
